### PR TITLE
Update node.js.yml

### PR DESCRIPTION
**Pull request by ShadowMonster99**
Change Notes:
- make workflow dispatch on manual call
- update to use git module from organization instead of local

### CODE REVIEW

**Comment by RoseTheFlower** [comment]
Thanks. I delete the branch and do over, since we're after a one-time change and the whole commit history isn't needed. I'll just incorporate the repo change by hand, while the push approach probably doesn't matter either way.

**Comment by RoseTheFlower** [comment]
It also breaks things, since the letter case change results in the new directory being ClassMapper, not classmapper.

**Comment by ShadowMonster99** [comment]
You should then change the workflow to use "ClassMapper" as it is the proper repository. Although you would have to do that as this PR was closed.

**Comment by RoseTheFlower** [comment]
It works either way, and it's more consistent with your current README instructions.

**Comment by ShadowMonster99** [comment]
It is best to change it though In case this repository is modified and my initial repository no longer points here. Its a good idea to future proof it. And thanks for reminding me to update my README!

**Pull request closed without merging**
