### PR TITLE
Soundtrack and SteamVR icon fixes

### PR DESCRIPTION
**Pull request by headassbtw**
fixes spacing for the soundtrack and SteamVR buttons, as well as adding the legacy SteamVR icon

image
image

### CODE REVIEW

**Comment by RoseTheFlower** [comment]
Thanks for the contribution. Is there a way to force the VR button to show without connecting a VR device?

**Comment by headassbtw** [comment]
yeah, install SteamVR

both states are visible without owning a headset, just relies on being installed, and the active state is with it running, headset connection doesn't matter

**Comment by RoseTheFlower** [comment]
Alright. Do you have a screenshot of the old Metro with it visible and/or in various states?

**Comment by headassbtw** [comment]
yep (turns out i lied about the "just running" part, i had to have my headset on for it to turn green):
image
image
image
image
being wider when active appears to be a bug that's cropped up as a result of the steam client updating

**Review by RoseTheFlower — APPROVED** [review]
Merging as a hotfix. I'll make adjustments in the next update.

**Comment by RoseTheFlower** [comment]
It seems that simply running SteamVR with no headset having been connected does not result in the icon displayed.

**Comment by headassbtw** [comment]
odd

**Comment by headassbtw** [comment]
just tried it out on my laptop, with no headset connected
installing and launching SteamVR then restarting steam makes the icon appear

**Comment by RoseTheFlower** [comment]
Yes, restarting is the way. Very helpful. Thanks.

**Pull request merged**
